top-shape:
	optirun python invert.py seed-top.json 0.7 0.001 shape

top-classic:
	optirun python invert.py seed-top.json 1 0.0001 classic

middle-shape:
	optirun python invert.py seed-middle.json 0.5 0.001 shape

middle-classic:
	optirun python invert.py seed-middle.json 0.1 0.0001 classic

wrong-dip-shape:
	optirun python invert.py seed-wrong_dip.json 1 0.001 shape

wrong-dip-classic:
	optirun python invert.py seed-wrong_dip.json 1 0.0001 classic

data:
	optirun python datagen.py
