shape: invert.py seeds.json data.xyz
	optirun python invert.py seeds.json 0.5 0.00005 shape

classic: invert.py seeds.json data.xyz
	optirun python invert.py seeds.json 0.01 0.0001 classic

clean:
	rm -rf *.pickle predicted-*.txt
