shape:
	optirun python invert.py seeds-shape.json 0.1 0.0001 shape

classic:
	optirun python invert.py seeds-shape.json 0.1 0.0001 classic

classic-full:
	optirun python invert.py seeds-classic.json 0.1 0.00005 classic
